server:
  port: 8080
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  application:
    name: hmdp
  datasource:
    driver-class-name: ${dp.spring.datasource.driver-class-name}
    url: ${dp.spring.datasource.url}
    username: ${dp.spring.datasource.username}
    password: ${dp.spring.datasource.password}
  redis:
    host: ${dp.spring.redis.host}
    port: ${dp.spring.redis.port}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug