dp:
  spring:
    profiles: dev
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
      username: root
      password: songzhikang719
    redis:
      host: 127.0.0.1
      port: 6379
      password: songzhikang719
